name: server CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

#env:
  #S3_BUCKET_NAME: ostargram

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'

      # Deploy
      - name: Deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.HOST }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.PRIVATE_KEY }}
        run:
          aws deploy create-deployment
          --application-name ostargram
          --deployment-group-name ostargram
          --file-exists-behavior OVERWRITE
          --region ap-northeast-2